### ISSUE TITLE
Bio.Alphabet module in PPD.py

### ISSUE THREAD

**Issue by ThibauldMichel** [Bean061/putative_paralog#2]
An error when running PPD.py due to importing IUPAC and Gapped from Bio.Alphabet, which is now outdated.

```
python ~/HybPiper/putative_paralog/PPD.py -h 
Traceback (most recent call last):
  File "~/HybPiper/putative_paralog/PPD.py", line 14, in <module>
    from Bio.Alphabet import IUPAC, Gapped
  File "/mnt/shared/scratch/usr/apps/conda/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by ThibauldMichel** [comment]
Deleting `from Bio.Alphabet import IUPAC, Gapped` solve the problem.

**Comment by Bean061** [comment]
Version 1.0.2 changed the biopython from 1.7.5 to 1.7.9, because Alphabet was removed from biopython, and added SeqRecord and Seq module.
